# Generated by Django 5.1.4 on 2024-12-15 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=100)),
                ('category_of_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecomm.category')),
            ],
        ),
    ]
