# Generated by Django 5.1.4 on 2024-12-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0002_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='sub_category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
