# Generated by Django 5.1.4 on 2024-12-16 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0003_alter_sub_category_sub_category_name'),
        ('products', '0002_product_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecomm.sub_category'),
        ),
    ]
